# This is a configuration module for sway, 
# Used to start pipewire, dbus and xdg-desktop-portal.

# Workaround for Audio and Screensharing on Gentoo/Openrc
exec dbus-update-activation-environment --all
exec dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec killall -q xdg-desktop-portal xdg-desktop-portal-wlr; sleep 1
exec gentoo-pipewire-launcher restart
exec snixembed --fork
