# This is a rofi module for sway
# including scripts for basic menus
# The packages used are:
# rofi, awww, cliphist and wl-paste.
# More will probably be added in the future.

  set $menu rofi -show drun
  bindsym $mod+Escape exec ~/.config/rofi/scripts/power.sh
  bindsym $mod+Print exec ~/.config/rofi/scripts/screenshot.sh
  bindsym $mod+Tab exec ~/.config/rofi/scripts/menu.sh
